#!/bin/zsh
local repo
case $1 in
  n)
    () {
      emulate -L zsh; setopt $_znap_opts

      repo=~znap/$2
      if [[ -d $repo ]]; then
        reply=( $repo )
        return 0
      fi
      return 66
    } "$@"
    ;;
  d)
    () {
      emulate -L zsh; setopt $_znap_opts

      for repo in ~znap/*(-/); do
        if [[ $2 == $repo(|/*) ]]; then
          reply=( $repo:t $#repo )
          return 0
        fi
      done
      return 66
    } "$@"
    ;;
  c)
    local expl tag='named-directories' group='named directory'
    _tags $tag
    _tags && _requested $tag expl $group &&
      compadd "$expl[@]" -I ']' -Q - ~znap/*(on-/:t)
    return
    ;;
esac
